name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm -C web build
      - run: pnpm -C backend build
      - name: Install Playwright Browsers
        run: pnpm -C qa exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm run ci
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: qa/playwright-report/
          retention-days: 30
